english_words/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("english_words_app.urls"))
]

english_words_app/urls.py
from django.urls import path

from .views import Words, Index, Register, CustomLoginView, CustomLogoutView, words_api

app_name = "english_words_app"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("dictionary/<slug:page>", Words.as_view(), name="word_list"),
    path("favorite/<slug:page>", Words.as_view(), name="favorite_list"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("api/v1/words/delete", words_api),
    path("api/v1/words/add", words_api),
]

english_words_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Word(models.Model):
    en = models.CharField(max_length=30)
    ru = models.JSONField(default=list, null=True)
    transcription = models.CharField(max_length=30, null=True, blank=True)
    data = models.JSONField(default=dict, null=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(Word, related_name="favorites")

english_words_app/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User


class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username']
        field_classes = {'username': UsernameField}

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

english_words_app/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, JsonResponse
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, TemplateView, FormView

from .forms import CustomUserCreationForm
from .models import Word, Profile
from .tools import shred

@csrf_exempt
@require_http_methods(["DELETE", "POST"])
def words_api(request: HttpRequest):
    user_id = request.GET.get("user_id")
    word_id = request.GET.get("word_id")
    profile = Profile.objects.get(user=User.objects.get(pk=int(user_id)))
    if not user_id or not word_id:
        return JsonResponse({"error": "bad request"}, status=400)
    if request.method == "DELETE":
        try:
            profile.favorites.remove(Word.objects.get(pk=int(word_id)))
        except (KeyError, Exception):
            return JsonResponse({"error": "bad request"}, status=400)
    else:
        try:
            profile.favorites.add(Word.objects.get(pk=int(word_id)))
        except (KeyError, Exception):
            return JsonResponse({"error": "bad request"}, status=400)
    return JsonResponse({"status": "ok"}, status=200)


class CustomLoginView(LoginView):
    template_name = "registration/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return self.get_redirect_url() or reverse_lazy("english_words_app:index")


class CustomLogoutView(LogoutView):
    template_name = "registration/logout.html"

    def get_success_url(self):
        return self.get_redirect_url() or reverse_lazy("english_words_app:index")


class Index(TemplateView):
    template_name = "english_words_app/index.html"

    def get_context_data(self, **kwargs):
        self.request.session["pages"] = None
        context = super().get_context_data(**kwargs)
        context["auth"] = self.request.user.is_authenticated
        return context

class Words(LoginRequiredMixin, ListView):
    _data_per_page = 10

    def get_queryset(self):
        if self.request.GET.get("next"):
            try:
                current_page = int(self.kwargs["page"]) + int(self.request.GET.get("next"))
            except TypeError as e:
                print(e)
                current_page = 0
        else:
            current_page = int(self.kwargs["page"])

        profile = Profile.objects.get(user=self.request.user)

        pages = self.request.session.get("pages")
        is_favorite = self.request.path.startswith("/favorite")
        if pages is None:
            if is_favorite:
                words = profile.favorites.order_by("?").values_list("pk", flat=True)
            else:
                words = Word.objects.order_by("?").values_list("pk", flat=True)
            pages = shred(self._data_per_page, words)
            self.request.session["pages"] = pages

        ids = pages[current_page % len(pages)]

        self.extra_context = {
            "is_favorite": is_favorite,
            "is_paginated": len(pages) > 1,
            "page": current_page,
            "favorites": [favorite.pk for favorite in profile.favorites.all()],
            "user": self.request.user
        }
        if is_favorite:
            return profile.favorites.filter(pk__in=ids)
        else:
            return Word.objects.filter(pk__in=ids)


class Register(FormView):
    form_class = CustomUserCreationForm
    template_name = "english_words_app/register.html"
    success_url = reverse_lazy("english_words_app:index")

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return super().form_valid(form)

english_words_app/templates/english_words_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block head %}
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-with initila-scale=1 shrink-to-fit=no">
	    <title>Magic Table</title>
	    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	{% endblock %}
</head>
<body>
	{% block body %}
		Hello World!
	{% endblock %}
</body>
</html>

english_words_app/templates/english_words_app/index.html
{% extends "english_words_app/base.html" %}

{% block body %}
	<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
		<div class="btn-group mx-auto">
			{% if auth %}
				<a class="btn btn-primary" href="{% url 'english_words_app:word_list' page=0 %}">Global Dictionary</a>
				<a class="btn btn-primary" href="{% url 'english_words_app:favorite_list' page=0 %}">Favorites</a>
				<form action="{% url 'english_words_app:logout' %}" method="post">
					{% csrf_token %}
					<button type="submit" class="btn btn-primary">Logout</button>
				</form>
			{% else %}
				<a class="btn btn-primary" href="{% url 'english_words_app:login' %}">Login</a>
			{% endif %}
			<a class="btn btn-primary" href="{% url 'english_words_app:register' %}">Register</a>
		</div>
	</div>
{% endblock %}

english_words_app/templates/english_words_app/register.html
{% extends "english_words_app/base.html" %}

{% block body %}
	<form method="post">
		<div class="form-group">
			{% csrf_token %}
			{{ form }}
		</div>
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
{% endblock %}

english_words_app/templates/english_words_app/word_list.html
{% extends "english_words_app/base.html" %}

{% block head %}
    {% load static %}
	<meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
	<script>
        var CSRF_TOKEN = '{{ csrf_token }}';
	</script>
    {{ block.super }}
{% endblock %}

{% block body %}
	{% csrf_token %}
    <div class="container">
        <div class="row">
            {% if not object_list %}
                <h3 class="text-center w-100">No words so far</h3>
            {% else %}
                <div class="col-12">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th class="clickable" id="enCol">En</th>
                                <th class="clickable" id="ruCol">Ru</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="words">
                            {% for word in object_list %}
                                <tr>
                                    <td class="white">{{ word.en }} ({{ word.transcription }})</td>
                                    <td class="white">
                                        {% for ru in word.ru %}
                                            {{ ru }}{% if not forloop.last %},{% endif %}
                                            {% if forloop.counter0|divisibleby:"2" and not forloop.last %}
	                                            <br>
	                                        {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% if word.pk in favorites %}
                                            <button type="button" class="btn btn-danger btn-width" value="{{ word.pk }}:{{ user.pk }}">Remove</button>
                                        {% else %}
                                            <button type="button" class="btn btn-primary btn-width" value="{{ word.pk }}:{{ user.pk }}">Add</button>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
	        {% endif %}
            <div class="col-12 d-flex justify-content-center align-items-center">
                <div class="btn-group">
                    {% if is_paginated %}
	                    {% if is_favorite %}
	                        <a class="btn btn-primary btn-padding btn-width" href="{% url 'english_words_app:favorite_list' page=page %}?next=-1"><code>&lt</code> Previous</a>
	                        <a class="btn btn-primary btn-padding btn-width" href="{% url 'english_words_app:favorite_list' page=page %}?next=1">Next <code>&gt</code></a>
	                    {% else %}
	                        <a class="btn btn-primary btn-padding btn-width" href="{% url 'english_words_app:word_list' page=page %}?next=-1"><code>&lt</code> Previous</a>
	                        <a class="btn btn-primary btn-padding btn-width" href="{% url 'english_words_app:word_list' page=page %}?next=1">Next <code>&gt</code></a>
                        {% endif %}
	                {% endif %}
                </div>
            </div>
	        <div class="col-12 d-flex justify-content-center align-items-center">
		        <a class="btn btn-warning" href="{% url 'english_words_app:index' %}">Back</a>
	        </div>
        </div>
    </div>
{% endblock %}